export const CHANGE_TAB = 'CHANGE_TAB';
export const FETCH_CURRENT_WORKOUT = 'FETCH_CURRENT_WORKOUT'; //async 1
export const FETCH_CURRENT_WORKOUT_COMPLETE = 'FETCH_CURRENT_WORKOUT_COMPLETE'; //async 2
export const ADD_EXCERCISE = 'ADD_EXCERCISE'; //async 1
export const ADD_EXCERCISE_COMPLETE = 'ADD_EXCERCISE_COMPLETE'; //async 2
